### ISSUE TITLE
please include binaries 

### ISSUE THREAD

**Issue by User3254548** [macedonga/whats-spoofing#2]
nobody wants to build apps

**Comment by macedonga** [comment]
if you aren't able to run a few simple commands then you shouldn't be using this code.

**Comment by macedonga** [comment]
it's to avoid skids. if you can build it then do it :-)

**Comment by macedonga** [comment]
i couldn't care less if people use it or not, it's just to add stuff for my portfolio
if you can't bother then don't use it
