### ISSUE TITLE
think it is bulshit.

### ISSUE THREAD

**Issue by hisbalah** [macedonga/whats-spoofing#3]
I can answer on the the message that has never existed, but it is stil on the right side like all my messages. and messages from the other side are still on the left.  And that is Bulshit, even if it looks like I am answering on spoofed message. Don"t you think?

**Comment by macedonga** [comment]
From what I can understand you didn't manage to get a working build yet :-)

Also, I'm still a student, and not looking for a job, what made you think otherwise?

(p.s.: it's cunt, not cun't lmao)
